# Generated by Django 4.0.2 on 2022-02-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttable',
            name='texttitle',
            field=models.ManyToManyField(blank=True, to='textdata.TextTitle'),
        ),
    ]
