# Generated by Django 4.0.2 on 2022-02-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textdata', '0002_alter_texttable_texttitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texttable',
            old_name='texttitle',
            new_name='item_text',
        ),
    ]
